---
title: "Methods"
author: "Adam Black"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Methods}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


This document describes the goals and methods used in the mepop package. The goal of this package (in its first iteration) is to provide population estimates by HSA, age, sex, and year.

Population estimates can come from two places. The gold standard is the US census that occurs every 10 years. In between the census official population estimates are released by the American Community survey. 

It is possible to get 5 year population estimates by age and sex and zip. However if we want 1 year estimates then the smallest geography we can get is county.


## County to HSA crosswalk

A County to HSA crosswalk is created from county to zip crosswalks by year downloaded from https://www.huduser.gov/portal/datasets/usps_crosswalk.html The zip to HSA crosswalk downloaded from the dartmouth atlas website. I think I'm using 2013 crosswalk. Maine's zip to HSA crosswalk does not change really at all over time. Since counties are larger than HSAs the goal is to create a crosswalk that attributes each county to one or more HSAs based on population. For example county 23001 is attributed as follows in 2010:
- 95% Lewiston
- 5% Farmington


## hsa_pop

Next we use the ACS population counts by age, sex, county, and year along with the county to hsa crosswalk to create population counts by age, sex, HSA, and year. After mulling the problem of yearly age-sex HSA population estimates over for a while this was the best idea I could come up with. It is obviously not ideal but I could not think of a better solution. The major assumption here is that the proportion defined in the county to HSA crosswalk are the same for all age groups. Of course this is not true but it might be good enough.


The output table is hsa_pop.


## Validation

A key part of this package is to provide vaidation that these population esitmates are OK. One approach is to compare the 5 year average of my estimates with the ACS 5 year estimates (ZCTA aggregated to HSA).

A second check is to look at the HSA population estimates in 2010 using the decentenial census.

We also might want to check both total aggregate numbers and summaries by age-sex group.


## SAE
A future goal for this package is to provide small area estimates of various census demographic variables such as poverty, insurance status, and education at the HSA level.

























